version: '3.9'

services:
  postgres:
    image: postgres:15
    container_name: church-postgres
    restart: always
    environment:
      POSTGRES_DB: church
      POSTGRES_USER: ${POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    #    ports:
    #      - "5432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    networks:
      - backend

  myapp:
    build: .
    container_name: church-spring-app
    depends_on:
      - postgres
    #    ports:
    #      - "8090:8090"
    volumes:
      - ./uploads:/uploads
    env_file:
      - .env
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/church
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
      MAIL_USERNAME: ${MAIL_USERNAME}
      MAIL_PASSWORD: ${MAIL_PASSWORD}
      UPLOAD_PATH: ${APP_UPLOAD}
    networks:
      - backend

  nginx:
    image: nginx:alpine
    container_name: church-nginx
    depends_on:
      - myapp
    ports:
      - "443:443"
      - "80:80"
    #    env_file:
    #      - .env
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./certs:/etc/nginx/certs:ro
    #    entrypoint: /bin/sh -c "envsubst '\$APP_PORT' < /etc/nginx/nginx.template.conf > /etc/nginx/nginx.template.conf && nginx -g 'daemon off;'"
    networks:
      - backend

networks:
  backend:
    driver: bridge
